### ISSUE TITLE
Can't upgrade to pro subscription

### ISSUE THREAD

**Issue by matrix0511** [bid-sniper/shopgoodwill-auction-sniper#17]
I just downloaded the shopgoodwill bid sniper for windows. But when I try to purchase the Pro version it won't take me to the screen to upgrade and purchase. Please advise.

I did see another mini box show in the background but I can't click on it to show it!! 

see attached screen shot.
<img width="334" alt="cant upgrade" src="https://github.com/bid-sniper/auction-sniper/assets/159946572/e9d6d0b7-b8f9-42de-92c0-4187208cf20c">

**Comment by bid-sniper** [comment]
Hi matrix0511,

We are currently experiencing issues, we will have an update released shortly...

**Comment by matrix0511** [comment]
Has this been fixed yet? Please let me know.

thanks

**Comment by bid-sniper** [comment]
Hi matrix0511,

Yes, this issue has been resolved and an update has been released this morning, please update to the latest version via the App Store!

**Comment by matrix0511** [comment]
Ok. but when I go out to Microsoft store to download it is taking forever to download. it just keeps spinning but never installs. see attached screen shot.
![long time to install](https://github.com/bid-sniper/auction-sniper/assets/159946572/7aed323f-3ee2-4b92-bbcb-fc0c878f6ef1)

**Comment by matrix0511** [comment]
Ok. I was able to finally get it installed. I upgraded to the pro version. I paid $50. But I just submitted several snipes in the tool.

But where do I go to see my active snipes? How do I manage them? I have been looking all over but there is no option to see my snipes. Please help!
![where are my snipes](https://github.com/bid-sniper/auction-sniper/assets/159946572/07665d31-ab28-442f-a826-fca6b726d814)

**Comment by bid-sniper** [comment]
The snipes should show in that grey bar on the main screen that reads "Add Snipes Above By Browsing..."

**Comment by matrix0511** [comment]
I think you guys need to do another update because this sniper tool is still broken and has a lot of issues. I have done about 5 different snipes using the tool for shopgoodwill but I still don't see my active snipes. Just now ONE snipe popped up. but where are all my other snipes??? this is soo frustrating! and I paid $50 for this tool and its not working.
![only 1 bid snipe showing](https://github.com/bid-sniper/auction-sniper/assets/159946572/03f867c9-c411-4bb1-bb96-b0682e60cbed)

**Comment by matrix0511** [comment]
I know but they are not showing up there.

**Comment by bid-sniper** [comment]
In order to add a snipe there you must go to any ShopGoodwill auction page from within the app and click the add snipe button on that page and then the item will show up in the grey bar snipe section.

**Comment by matrix0511** [comment]
I don't think you are listening to what I'm saying. I have done ALL OF THAT already. it's not working!

Please see attached a video of what I'm doing. I'm following the steps EXACTLY has you said but it's STILL NOT ADDING MY SNIPES. Please see video and please advise on how to fix this ASAP.

Please extract the zip file to watch the video!
[Recording of issue.zip](https://github.com/bid-sniper/auction-sniper/files/14291074/Recording.of.issue.zip)

**Comment by bid-sniper** [comment]
When you enter item is down at the bottom you are adding the snipe manually but instead try clicking the add snipe button directly on the item page under the large place bid button

**Comment by matrix0511** [comment]
Ok. but now even when I close out the tool and open again I see this error message that keeps popping up at the top right corner.

See attached screen shot.
![error](https://github.com/bid-sniper/auction-sniper/assets/159946572/0f013626-a8ff-4741-94fd-7dea7a7fca16)

**Comment by bid-sniper** [comment]
That error is being produced by the website not the app, it sounds like your computer is experiencing some kind of issue based on what you explained earlier about the download being slow, perhaps you might try uninstalling and then reinstalling?

**Comment by islandoflotuseaters** [comment]
Hi again, I actually came here because I'm getting the same error as matrix, I think it's what was happening before it deactivated, though I didn't get to test it at that point, but now I've tested it a lot more over the last couple of days, so I can give a little more info:

 It happens after every single snipe, the initial snipe works perfectly, but after that listing pages and my favorites section, won't populate with any actual listings, I am unable to add any new listings from the bottom when I pull an Auction Id off of another browser and I get that same pop-up. If I just leave it, even snipes I already have loaded will fire off, but the bids never actually get entered into the site.

In order to fix it, I just log out in the app and then log back in and it works perfectly, but only for next snipe before the cycle repeats itself, so obviously having to resign in manually every time kind of defeats the purpose of the app.

**Comment by matrix0511** [comment]
Ok I took your advice and uninstalled and re-installed. It appears to be working but its now prompting me to purhase again. 

but i already upgraded and paid you $50. So how do I get past this prompt? is there some place to enter my license?

and can you please email me my license number? 
![where is my license](https://github.com/bid-sniper/shopgoodwill-auction-sniper/assets/159946572/5cb72c5b-1cd3-4c4a-83f3-bd965242821d)

**Comment by bid-sniper** [comment]
Hi islandoflotusers,

Can you please record a video of the problem occurring and send it to us?

**Comment by matrix0511** [comment]
Wait…you want me to pay you another $50??

Why can’t you just refund me my money back that I have already paid you?

Do I need to contact PayPal and report this as fraud or something?? Because
I’m starting to feel like I got ripped off.

Not feeling good about this at all.

Please advise ASAP.

John

**Comment by matrix0511** [comment]
I don’t have another $50 to pay you. This should be addressed without me having to give you more money.

please refund me my $50 I paid please

**Comment by islandoflotuseaters** [comment]
> Hi islandoflotusers,
> 
> Can you please record a video of the problem occurring and send it to us?

I'm not really set-up to screen record right now, but it's easily repeatable as it happens every single time. After every single snipe, nothing will load 
<img width="1213" alt="Screenshot 2024-02-15 171101" src="https://github.com/bid-sniper/shopgoodwill-auction-sniper/assets/45557576/6194dbbf-b733-4fae-bd91-85d41821c025">
Favorites can't be pulled and individual listing pages just won't load. Then I logout on the app and log back in and everything works perfectly as it should
<img width="1027" alt="Screenshot 2024-02-15 171204" src="https://github.com/bid-sniper/shopgoodwill-auction-sniper/assets/45557576/d4362c7f-6220-4284-a6c7-cde681b6fd0b">
Literally all I did between those two screenshots is logout and then log back in. For the record, when I used the old download version in the past, this never happened, but since I started using the Microsoft Store version it has.

**Comment by bid-sniper** [comment]
Matrix0511,

We have cancelled your license and refunded your money but please do not bring your business back to us! We are refusing service to you as of now. You are permanently banned!!! Take your business elsewhere please we don't want users like you!

**Comment by bid-sniper** [comment]
Matrix0511,

We have canceled and refunded your payment and you have been permanently banned, please take your business elsewhere.

**Comment by bid-sniper** [comment]
Islandoflotofusers,

Next time post a message on your own issue don't comment on another customers issue or we will ban you too! Because of you this customer got upset and we kicked them out if you do one more thing wrong we will kick you out too. Don't come over here looking for trouble cause we will kick you out!

**Comment by islandoflotuseaters** [comment]
My bad, I figured you would rather me just include it here rather than open a new issue and have new viewers just see a bunch of open issues. I'll go add it now.

**Comment by bid-sniper** [comment]
That's ok, that customer was already a rude irate customer since yesterday I had been hearing him talk crazy to me and I finally got him to simmer down a little and your comment on his thread flared him back up I'm sorry but I just couldn't be patient anymore as he verbally bashed me, no problem, I will take a look at the screenshots you sent me and see if I can get a better update released by tomorrow...
